name: build-mod
on:
  workflow_dispatch:
  release:
    types: [created]
  pull_request:

permissions: read-all

jobs:
  build-the-mod:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
    steps:
      - uses: argonui/TTSModManager.action@v1.0.0

